name: Build all targets and run all tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build_and_test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bazelisk build //...
